name: wdio-cucumber-chrome tests
on:
    push:
        branches: [master]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.17.0]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14.x'
                
            - name: install all dependencies
              run: npm i
            - name: run tests and create report
              run: npm run test:chrome:headless

            - name: Upload artifact cucumber-html-reporter
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-html-reporter
                  path: ./report
                  retention-days: 5 
            - name: Deploy to pages
              if: always()
              uses: peaceiris/actions-gh-pages@v3.7.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./report